---
abstract: 'A JIT HTTP server'
author:
  - LNATION
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.7702, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hypersonic
no_index:
  directory:
    - t
    - inc
recommends:
  Devel::CheckLib: '0'
  ExtUtils::PkgConfig: '0'
requires:
  Cpanel::JSON::XS: '0'
  XS::JIT: '0.13'
  perl: '5.010'
resources:
  bugtracker: https://github.com/ThisUsedToBeAnEmail/Hypersonic/issues
  repository: https://github.com/ThisUsedToBeAnEmail/Hypersonic.git
version: '0.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
